Hej Therese! 
Mina kommentarer i koden kanske inte är skrivna på ett sätt som är brukligt. Jag har primärt gjort kommentarera för att jag själv ska förstå vad som händer i koden. Hoppas det är okay :-) 

# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [ ]:
A = np.arange(1, 16).reshape(3,5) 

In [ ]:
A = np.arange(1, 16).reshape(3,5) # skapar en numpy aray med tal 1-15 (16 är är ett stopptal) samt 3x5 matris
print(A.ndim) # skriver ut dimension
print(A.shape) 
print(A.size)
print(A.dtype)
print(A.itemsize) # hur många byte varje element tar i minne

2
(3, 5)
15
int64
8


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
# Skapar en array med talen 1–9 och formar den till en 3x3-matris (innehåller heltal, dtype=int)

C = np.ones((3, 3))*2
# Skapar en 3x3-matris av ettor (float) och multiplicerar varje element med 2 -> en float-matris av tvåor

print(B)
print()
print(C)

print("--------")

resultat_s = B - C
print(resultat_s)
print("--------")

resultat_m = B * C 
print(resultat_m)
print("--------")

resultat_mm = B @ C
print(resultat_mm)
print("--------")


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [15]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
D = np.arange(1, 10).reshape(3, 3)

exponentiera = np.exp(D)
# Beräknar e^x för varje element i D (elementvis)
print(exponentiera)

In [28]:
# minsta värdet i matrisen
D = np.arange(1, 10).reshape(3, 3)
minsta = D.min()
print(minsta)


# Hittar minsta talet i hela matrisen (1)

1


In [30]:
#  Minsta värdet i varje rad
minsta_perrad = D.min(axis=1) # axis=1 betyder "per rad"
print(minsta_perrad)

#  Minsta värdet i varje rad
minsta_perkolumn = D.min(axis=0) # axis=0 betyder "per kolumn"
print(minsta_perkolumn)


[1 4 7]
[1 2 3]


In [31]:
# Index för minsta värdet i hela matrisen (np.argmin)
index = np.argmin(D) # Returnerar index i den flata arrayen (0), eftersom 1 är första elementet
print(index)

0


In [32]:
# Indexvärdet för minsta värdet i varje rad
index_rad = np.argmin(D, axis=1) # axis=1 = per rad
print(index_rad)

[0 0 0]


In [ ]:
#Summa av alla element
sumElement = D.sum() # 1+2+3+4+5+6+7+8+9 = 45
print(sumElement)


#Medelvärde per kolumn
sumPerKolumn = D.mean(axis=0) 
print(sumPerKolumn)

#Median per kolumn

medianKolumn = np.median(D, axis=0)
print(medianKolumn)


45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [38]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [39]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
import numpy as np

# Skapar matrisen A (3 rader, 5 kolumner)
A = np.arange(1, 16).reshape(3, 5)

print("Matris A:")
print(A)
print()

# När vi skriver A[1] ger vi bara ett index, trots att A är 2D.
row = A[1]
print("A[1] (rad 1):")
print(row)
print()

# Förklaring:
# A har två axlar (rad- och kolumnaxeln).
# Genom att skriva A[1] anger vi bara index för första axeln (raden).
# Den andra axeln "antyds" då som ':' (alla kolumner).
# Det betyder att A[1] är samma som A[1, :]

print("A[1, :] (explicita kolonslicing):")
print(A[1, :])

Matris A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

A[1] (rad 1):
[ 6  7  8  9 10]

A[1, :] (explicita kolonslicing):
[ 6  7  8  9 10]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
# Jag testade med iteratörerna flat och nditer

#for i in A: #itererar rad för rad (första axeln)
#    print(i)

for f in A.flat: #itererar ett tal i taget
    print(f)

#for nd in np.nditer(A): #generell iterator
#    print(nd)



### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [26]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [34]:
# Det betyder att vi har skapat en 3D matris

import numpy as np

a = np.arange(30) #Skapar en matris med talen 0–29

b = a.reshape((2, 3, -1)) #Formar om arrayen till en 3D-array:
# 2 block
# 3 rader per block
# -1 NumPy räknar ut hur många kolumner som behövs

print(a)

print()

print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])


# m1 har shape (2, 2)
# m2 har shape (2,)

# Numpy upprepar raden i m2 
#[ [1, 2],     [ [1, 1],     [ [2, 3],
#  [3, 4] ]  +   [1, 1] ]  =   [4, 5] ]

print(m1)
print()
print(m2)
print()
print(m1 + m2)

[[1 2]
 [3 4]]

[1 1]

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [39]:
v1 = np.array([1, 2, 3])

# v1 har shape (3,)
# 1  är alltså  [1, 1, 1]

print(v1)
print(v1 + 1)



[1 2 3]
[2 3 4]


In [ ]:
#Skapar talserie och matris
A = np.arange(1, 5).reshape(2,2)
print(A)
print()

#Skapar en array med talen 2 och 2
b = np.array([2, 2])
print(b)
print()

# Genom Broadcasting så upprepas b radvis
print(A + b)

[[1 2]
 [3 4]]

[2 2]

[[3 4]
 [5 6]]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [57]:
 # Min funktion för att räkna matriser samt validera att de har samma shape etc

import numpy as np

def add_matris(A, B, operation):
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
    #if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):    
        raise TypeError("Fel! Du måste använda array av typen np.ndarray")

    if operation not in ("add", "multiply"):
        raise ValueError("Måste vara add och multiply")


    if operation == "add":
        if A.shape != B.shape:
            raise ValueError("matriserna måste vara samma shape")
        return A + B

    if operation == "multiply":
        if A.shape[1] != B.shape[0]:
            raise ValueError("matriserna måste vara samma antal kolumner och rader ")
        return A @ B


A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(add_matris(A, B, "add"))
print(add_matris(A, B, "multiply"))





[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [ ]:
#10.1.1 
#a
import numpy as np
#a

x = np.array([4, 3])

# Dimension (antal axlar)
print(x.ndim)      # 1 (endimensionell array)

# Antal element (vektorns dimension )
print(x.size)      # 2

# Shape (form)
print(x.shape)     # (2,)




In [ ]:
#10.1.1 
#b
import numpy as np

x = np.array([4, 3])

# Skalärmultiplikation
r = 5 * x

print(r)

[20 15]


In [ ]:
#10.1.1 
#c
import numpy as np
x = np.array([4,3])
r = 3 * x
print(r)


[12  9]


In [ ]:
#10.1.1 
#d
import numpy as np

x = np.array([4, 3])

# Beräknar 5x + 3x
r = 5 * x + 3 * x

print(r)

[32 24]


In [7]:
#10.1.1 
#e
import numpy as np
x = np.array([4,3])
r = 8 * x
print(r)

[32 24]


In [8]:
#10.1.1 
#f
import numpy as np
x = np.array([4, 3])
r = 4 * x - x
print(r)

[12  9]


In [ ]:
#10.1.1 
#g
import numpy as np
x = np.array([4, 3])
t = x.T
print(x.shape) 
print(t.shape)
# den har samma dimension efter transponering  

(2,)
(2,)


In [ ]:
#10.1.1 
#h
# x är en radvektor och xT är en kolumnvektor = är inte definierat 

In [12]:
#10.1.1 
#i
import numpy as np         
x = np.array([4, 3])
norm_x = np.linalg.norm(x)      # Beräknar normen (längden) av vektorn x
print(norm_x)                   

5.0


In [ ]:
#10.1.2 
#a, b, c, d, e och f

import numpy as np                  # Importerar NumPy-biblioteket

v = np.array([[3], [7], [0], [11]]) # Definierar kolumnvektorn v (4x1)

#a
print(v.shape)                      # Skriver ut dimensionen (4, 1)

#b
result_b = 2 * v                    # Beräknar 2v genom att multiplicera varje element med 2
print(result_b)                     # Skriver ut resultatet av 2v

#c
result_c = 5 * v + 2 * v            # Beräknar 5v + 2v (kan förenklas till 7v)
print(result_c)                     

#d
result_d = 4 * v - 2 * v            # Beräknar 4v - 2v (kan förenklas till 2v)
print(result_d)                     

#e
T = v.T    
print()                          # Transponerar v från (4x1) till (1x4)
print(T)                   
print(T.shape)                    # Skriver ut nya dimensionen efter transponering (1, 4)
print()

#f
norm_v = np.linalg.norm(v)          # Beräknar normen (längden) av v
print(norm_v)                       # Skriver ut normen av v

In [17]:
#10.1.3 
#a och b

import numpy as np                

#a
v1 = np.array([4, 3, 1, 5])             # Definierar v1
v2 = np.array([2, 3, 1, 1])             # Definierar v2

norm_v1 = np.linalg.norm(v1)            # Beräknar normen (längden) av vektorn v1
print(norm_v1)                          # Skriver ut ||v1||

#b
diff = v1 - v2                          # Beräknar vektorskillnaden v1 - v2 elementvis
norm_diff = np.linalg.norm(diff)        # Beräknar normen av v1 - v2
print(norm_diff)                        # Skriver ut ||v1 - v2||

7.14142842854285
4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
#10.2.1
# a till l
import numpy as np

# Definierar matriserna enligt uppgiften
A = np.array([[2, 1, -1],
              [1, -1, 1]])  # A är 2x3

B = np.array([[4, -2, 1],
              [2, -4, -2]])  # B är 2x3

C = np.array([[1, 2],
              [2, 1]])  # C är 2x2

D = np.array([[3, 4],
              [4, 3]])  # D är 2x2

E = np.array([[1],
              [2]])  # E är 2x1

I = np.array([[1, 0],
              [0, 1]])  # I är 2x2 (identitetsmatris)

#a 2A
a_result = 2 * A  # Multiplicerar varje element i A med 2
print("a) 2A =\n", a_result, "\n")  # Skriver ut resultatet

#b B - 2A
b_result = B - 2 * A  # Beräknar 2A och subtraherar elementvis från B
print("b) B - 2A =\n", b_result, "\n")  # Skriver ut resultatet

#c 3C - 2E  (kontrollerar om det är definierat)
if C.shape == E.shape:  # Kollar om C och E har samma dimension (krav för addition/subtraktion)
    c_result = 3 * C - 2 * E  # Skulle räkna om det vore tillåtet
    print("c) 3C - 2E =\n", c_result, "\n")  # Skriver ut resultatet
else:
    print("c) 3C - 2E är inte definierat (olika dimensioner:", C.shape, "och", E.shape, ")\n")  # Förklarar varför

#d 2D - 3C  (kontrollerar om det är definierat)
if D.shape == C.shape:  # Kollar om D och C har samma dimension (krav för subtraktion)
    d_result = 2 * D - 3 * C  # Utför subtraktionen elementvis
    print("d) 2D - 3C =\n", d_result, "\n")  # Skriver ut resultatet
else:
    print("d) 2D - 3C är inte definierat (olika dimensioner)\n")  # Skriver ut felorsak

#e D^T + 2D
e_result = D.T + 2 * D  # Transponerar D och adderar med 2D (elementvis)
print("e) D^T + 2D =\n", e_result, "\n")  # Skriver ut resultatet

#f 2C^T - 2D^T  (kontrollerar om det är definierat)
if C.T.shape == D.T.shape:  # Kollar om transponaten har samma dimension
    f_result = 2 * C.T - 2 * D.T  # Utför subtraktionen elementvis
    print("f) 2C^T - 2D^T =\n", f_result, "\n")  # Skriver ut resultatet
else:
    print("f) 2C^T - 2D^T är inte definierat (olika dimensioner)\n")  # Skriver ut felorsak

#g A^T - B  (kontrollerar om det är definierat)
if A.T.shape == B.shape:  # Kollar om A^T och B har samma dimension
    g_result = A.T - B  # Skulle räkna om det vore tillåtet
    print("g) A^T - B =\n", g_result, "\n")  # Skriver ut resultatet
else:
    print("g) A^T - B är inte definierat (dimensioner:", A.T.shape, "och", B.shape, ")\n")  # Förklarar varför

#h AC  (matrismultiplikation: kolumner i A måste = rader i C)
if A.shape[1] == C.shape[0]:  # Kollar multiplikationsvillkoret
    h_result = A @ C  # Beräknar matrisprodukten
    print("h) AC =\n", h_result, "\n")  # Skriver ut resultatet
else:
    print("h) AC är inte definierat (A:", A.shape, ", C:", C.shape, ")\n")  # Förklarar varför

#i CD  (matrismultiplikation: kolumner i C måste = rader i D)
if C.shape[1] == D.shape[0]:  # Kollar multiplikationsvillkoret
    i_result = C @ D  # Beräknar matrisprodukten
    print("i) CD =\n", i_result, "\n")  # Skriver ut resultatet
else:
    print("i) CD är inte definierat (C:", C.shape, ", D:", D.shape, ")\n")  # Förklarar varför 

# (j) CB  (matrismultiplikation: kolumner i C måste = rader i B)
if C.shape[1] == B.shape[0]:  # Kollar multiplikationsvillkoret (2 == 2)
    j_result = C @ B          # Beräknar matrisprodukten CB
    print("j) CB =\n", j_result, "\n")  # Skriver ut resultatet
else:
    print("j) CB är inte definierat (C:", C.shape, ", B:", B.shape, ")\n")  # Förklarar varför

# (k) CI  (matrismultiplikation: kolumner i C måste = rader i I)
if C.shape[1] == I.shape[0]:  # Kollar multiplikationsvillkoret (2 == 2)
    k_result = C @ I          # Beräknar matrisprodukten CI (ska bli C)
    print("k) CI =\n", k_result, "\n")  # Skriver ut resultatet
else:
    print("k) CI är inte definierat (C:", C.shape, ", I:", I.shape, ")\n")  # Förklarar varför

# (l) AB^T  (matrismultiplikation: kolumner i A måste = rader i B^T)
if A.shape[1] == B.T.shape[0]:  # Kollar multiplikationsvillkoret (3 == 3)
    l_result = A @ B.T          # Beräknar matrisprodukten AB^T
    print("l) AB^T =\n", l_result, "\n")  # Skriver ut resultatet
else:
    print("l) AB^T är inte definierat (A:", A.shape, ", B^T:", B.T.shape, ")\n")  # Förklarar varför





In [ ]:
#10.2.2
import numpy as np                        

A = np.array([[2, 3, 4],                   # Definierar matrisen
              [5, 4, 1]])

A_T = A.T                                  # Transponerar A (byter rader och kolumner)

result = A @ A_T                           # Beräknar matrisprodukten A · A^T

print(result)                              # Skriver ut resultatet av A A^T

[[29 26]
 [26 42]]


In [21]:
#10.2.1
import numpy as np                                      # Importerar NumPy-biblioteket

A = np.array([[1, 2],                                   # Definierar matrisen 
              [2, 4]])

B = np.array([[2, 1],                                   # Definierar matrisen 
              [1, 3]])

C = np.array([[4, 3],                                   # Definierar matrisen
              [0, 2]])

AB = A @ B                                               # Beräknar matrisprodukten AB
AC = A @ C                                               # Beräknar matrisprodukten AC

print(AB)                                                # Skriver ut AB
print()                                                  # 
print(AC)                                                # Skriver ut AC

print()                                                  
print(np.array_equal(AB, AC))                             # Verifierar att AB = AC (True om lika)

print()                                                 
print(np.array_equal(B, C))                               # Verifierar att B = C (False om olika)

[[ 4  7]
 [ 8 14]]

[[ 4  7]
 [ 8 14]]

True

False


### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
import numpy as np

# Skapar en array med 4 heltal
v1 = np.arange(4)

# Tar en slice av de två sista elementen 
v2 = v1[-2:]

print("v1:", v1)  # Skriver ut originalarrayen
print("v2:", v2)  # Skriver ut vyn (slicen)
print()

# Kollar om v2 är en view av v1:
# Om v2.base pekar på v1 (eller en array som i sin tur pekar på v1) så är det en view
print("v2.base:", v2.base)  # Om detta inte är None så är v2 en view (delar data med någon annan array)
print("v2 är view av v1?:", v2.base is v1)  # True betyder att v2 direkt är en view av v1
print()

# Ändrar sista elementet i v2
v2[-1] = 123

print("Efter ändring v2[-1] = 123")
print("v1:", v1)  # Om v2 är en view, syns ändringen även här
print("v2:", v2)